server:
  port: 8081
  
spring:
  data:
    mongodb:
      uri: your mongodb uri
      database: savings-account-spring-boot
      
  application:
    name: Savings Account Service

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 
            clientSecret: 
          google:
           clientId: 
           clientSecret:
          
