server:
  port: 8081
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://codingz2m:d1YiOyjWh1qimx8L@cluster0.qqtuvzs.mongodb.net/?retryWrites=true&w=majority
      database: savings-account-spring-boot
      
  application:
    name: Savings Account Service


    
